/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct entradas {
	float num1;
	float num2;
	char operador;
};
typedef struct entradas entradas;

#define CALCULADORA_PROG 0x2fffffff
#define CALCULADORA_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  float * suma_1(entradas *, CLIENT *);
extern  float * suma_1_svc(entradas *, struct svc_req *);
#define RESTA 2
extern  float * resta_1(entradas *, CLIENT *);
extern  float * resta_1_svc(entradas *, struct svc_req *);
#define MULT 3
extern  float * mult_1(entradas *, CLIENT *);
extern  float * mult_1_svc(entradas *, struct svc_req *);
#define DIV 4
extern  float * div_1(entradas *, CLIENT *);
extern  float * div_1_svc(entradas *, struct svc_req *);
extern int calculadora_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  float * suma_1();
extern  float * suma_1_svc();
#define RESTA 2
extern  float * resta_1();
extern  float * resta_1_svc();
#define MULT 3
extern  float * mult_1();
extern  float * mult_1_svc();
#define DIV 4
extern  float * div_1();
extern  float * div_1_svc();
extern int calculadora_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_entradas (XDR *, entradas*);

#else /* K&R C */
extern bool_t xdr_entradas ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
